source/css/_layout/post.styl
在手機上如果 code block 很長的時候
那個按鈕會跑掉
=> fix bug of the clip button

source/js/search/local-search.js
fixed:
1. local search is broken when not on home pages (like Tags and Categories page)
2. disable scrolling when toggle search box
=> Fix bugs of search

languages/zh-Hans.yml, layout/includes/footer.pug, layout/includes/layout.pug, layout/post.pug, source/js/scroll.js
Note: Every improvement has already be separated into single commit.
=> Some improvements

_config.yml, layout/includes/comments/gitalk.pug, layout/includes/comments/index.pug, layout/includes/head.pug
首先感谢 @Molunerfinn 提供的主题，很好用。
评论系统，我自己没disqus号，而且国内也访问不了，所以我选择了gitment。
但我发现用了gitment，它的依赖https://imsun.github.io/gitment/dist/gitment.browser.js
也要翻墙才能正常访问，一时也没找到它的国内镜像。所以我就依葫芦画瓢增加了个评论的：
[gitalk](https://github.com/gitalk/gitalk)
成功用上了，如果有类似的情况的同学可以用用。
=> added: gitalk support

layout/includes/layout.pug, layout/includes/slide/script.pug
设置了子目录的情况下，js和css的路径无法正常加载
url: http://yoursite.com/child
root: /child/
=> there some problems in path of js and css

source/css/_layout/head.styl
1.  博客名 略微加了点 text-shadow （也许您的初衷就是保持扁平吧）
2.  menu菜单加了个hover交互 ，横线， 使用了theme-color
=> 很喜欢您的melody主题，已使用。希望能尽点微薄之力，添加了一小点样式改动：

_config.yml, languages/default.yml, languages/en.yml, languages/zh-Hans.yml, layout/includes/config.pug, layout/includes/search/local-search.pug, source/js/search/algolia.js, source/js/search/local-search.js
I added Chinese language support for Algolia and local search, which take advantage of  the yml files under the language folder.  In this way, it will be much more extensible.
=> Added: search language support

source/js/search/algolia.js, source/js/search/local-search.js
I hope this function is helpful to you.
=> Added: Esc shortcut to close search

_config.yml, layout/includes/head.pug
Add some favicons and `theme-color`, users can ignore if they do not want to set.
=> Added: PWA favicons for all platforms

_config.yml, languages/default.yml, languages/en.yml, languages/zh-Hans.yml, layout/includes/head.pug, layout/includes/layout.pug
A little change, and maybe you want to just keep them in English? Anyway, I change the title to use languages files for extensibility.
=> Fixed: title languages of Archives, Category, and Tag

layout/includes/count/busuanzi.pug
=> busuanzi 更换了域名

_config.yml, layout/includes/third-party/katex.pug, source/css/_layout/post.styl, source/js/katex.js
和上一个 PR 一样，解决了 KaTex 超过屏幕宽度的问题。
这次和 dalao 说的一样加了个 wrapper div 然后将 css 选择到了 div 上进行操作~
=> 以更优的方式解决了 KaTex 问题！

layout/includes/share/index.pug, layout/includes/share/share-js.pug
=> sharejs 调整

languages/default.yml, languages/en.yml, languages/zh-Hans.yml, layout/post.pug
=> post_meta.date_type新增both选项

_config.yml
=> :bug: Fix: word error in _config.yml

README.md
Deleted a link that is not valid and added a new link~
=> :package: Chore: update demo sites

_config.yml, layout/includes/head.pug
Add another option for custom text for users to choose
=> :sparkles: Feature: add hitokoto

source/css/_layout/post.styl
=> :bug: Fix: img style can effect custom image on footer

layout/page.pug
=> :hammer: Refactor: simplify include comments

_config.yml, layout/includes/comments/valine.pug, source/css/_layout/post.styl
#277 
加上了新的记录IP选项
（把上游分支合并过来，但是之前的 commits 还是在，就不用在意啦😝
=> :bug: Fix: #277 and add new feature

layout/post.pug
For example, display URLcode in Chinese.
=> :bug: Fix: URL display problem in some environments

_config.yml, layout/includes/comments/index.pug, layout/includes/comments/vssue.pug
Add Vssue comment system (support to store comments in gitlab, github and some other platforms)
ISSUES CLOSED: #297
=> :sparkles: Feature(comment): add vssue comment system

layout/includes/slide/layout.pug, layout/includes/slide/script.pug
The change log is here: https://github.com/hakimel/reveal.js/releases/tag/4.1.0
P/S: Hi there, would mind publish the new package to npm. Thanks.
=> :arrow_up: Upgrade(deps) reveal.js

layout/includes/head.pug
sorry I make a wrong, so I think i should fix that myself.
=> :bug: Fix: tab error

source/js/search/local-search.js
=> :bug: Fix: post page search

_config.yml, layout/includes/comments/index.pug, layout/includes/comments/waline.pug
see https://github.com/Molunerfinn/hexo-theme-melody/issues/330
=> Add waline support
